# Jekyll site
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Internal Consumption(a3c9864f-b1af-4cc5-8dec-8753956e8ff2)'
    appType: 'webAppLinux'
    WebAppName: 'benappserdemo'
    deployToSlotOrASE: true
    ResourceGroupName: 'BenAKSDemo'
    SlotName: 'test'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
# Package your Jekyll site using the jekyll/builder Docker container image.
# Add steps that build, test, save build artifacts, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@0
  displayName: 'Run Jekyll'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'jekyll/builder:latest'
    volumes: |
      $(build.sourcesDirectory):/srv/jekyll
      $(build.binariesDirectory):/srv/jekyll/_site
    containerCommand: 'jekyll build --future'
    detached: false
